# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4df3ec374f639b1e9fd04139b3700be8f7c7c5eeda1c939abac838413f2afad9b667b395a6a055b157a928607bc6606a06472a4841792911fb4abde981cc8aa8

test:
  secret_key_base: 55687ce37f4860acb3ff3e5ed04419c7e31900ec0b6e28745ac1249cdd71efc45001257c6d32ec66fc26da0c84477b7e3322eec30430e34c9046120103269dc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
